#!/usr/bin/env node
const { spawn, execSync } = require(`child_process`)
try{
  execSync(`scripts/build-babel`,[],{stdio:`inherit`})
  spawn(`scripts/watch-babel`,[],{stdio:`inherit`})
  spawn(`scripts/watch-remove`,[],{stdio:`inherit`})
  spawn(`scripts/watch-nodemon`,[],{stdio:`inherit`})
}
catch(e){
  console.error(e)
}
