#!/usr/bin/env node
const srcPath = `app`;
const distPath = `dist`;
const fs = require(`fs`);
const rimraf = require(`rimraf`);
const watch = require(`node-watch`);
watch(srcPath,{recursive: true},function(evt, name){
  if(evt==`remove`){
    name = distPath+name.substr(srcPath.length);
    if(fs.existsSync(name)){
      rimraf.sync(name);
    }
  }
})
